spring:
    datasource:
        url: jdbc:h2:file:~/dev/data/springplay/h2/demo;MODE=MSSQLServer

        driverClassName: org.h2.Driver
        username: sa
        password: password
        initialization-mode: always
        continue-on-error: true

logging:
    level:
        root: DEBUG

springplay:
    security:
        jwt-key: ThisIsAJWTSignatureSample
