spring:
    datasource:
        url: jdbc:h2:file:./backend/src/main/resources/db/demo;MODE=MSSQLServer
        driverClassName: org.h2.Driver
        username: sa
        password: password
        initialization-mode: always
        continue-on-error: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect

logging:
    level:
        root: DEBUG

springplay:
    security:
        jwt-key: ThisIsAJWTSignatureSample
