spring:
    datasource:
        url: jdbc:sqlserver://localhost:1433;database=ceserver
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        username: sa
        password: p@ssw0rd
